import { useState } from 'react';
import GameButton from '@/components/game/GameButton';
import ShopOffer from '@/components/game/ShopOffer';
import PurchasePicker from '@/components/game/PurchasePicker';
import IntermissionInventory from '@/components/game/IntermissionInventory';
import { legalLoadout } from '@/game/progression/runRules';
import { TUNING, signalForLevel } from '@/game/data/tuning';
import { sfx } from '@/game/audio';
export default function ShopScreen({run,onAction,onContinue,onProfile}) {
  const [pending,setPending]=useState(null),[error,setError]=useState('');
  const act=event=>{try{onAction(event);setError('');if(event.type==='buy')setPending(null);sfx(event.type==='reroll'?'reroll':event.type==='buy'?'purchase':'pickup')}catch(e){setError(e.message)}};
  const buy=item=>{if(item.premium || (item.baseId && !legalLoadout(run.character,[...run.weapons,item])))setPending(item);else act({type:'buy',offerId:item.id})};
  const cost=TUNING.rerollBase+run.shop.rerolls*TUNING.rerollStep;
  return <main className="van-shop min-h-screen p-5 text-game-ink sm:p-9"><div className="mx-auto max-w-6xl"><header className="flex flex-wrap justify-between gap-4"><div><p className="font-bold uppercase tracking-widest text-game-warm">Company van • Wave {run.wave} complete</p><h1 className="mt-2 font-heading text-3xl font-bold sm:text-4xl">Between-wave shop</h1><p className="mt-2 text-sm text-game-muted">Locks {run.lockedIds.length}/2 • Rare deployables are not guaranteed.</p>{run.lastWaveMetrics && <p className="mt-2 text-xs text-game-muted">This wave: {run.lastWaveMetrics.kills} repairs • {run.lastWaveMetrics.xpEarned} XP • {run.lastWaveMetrics.levelsGained} levels (early target ≈{TUNING.targetEarlyLevelsPerWave})</p>}</div><div className="rounded-xl bg-game-panel p-4 text-sm"><p className="font-bold text-game-signal">Spendable Signal: {Math.round(run.signal)}</p><p className="mt-1">Total earned Signal: {Math.round(run.earnedSignal || 0)}</p><p className="mt-1">XP: {run.xp.toFixed(1)} / {signalForLevel(run.level)} • Level {run.level}</p></div></header>{error && <p role="alert" className="mt-5 rounded-xl border border-game-warm/30 bg-game-panel p-4 text-game-warm">{error}</p>}<div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{run.shop.offers.map((item,index)=><ShopOffer key={item?.id || index} item={item} run={run} locked={!!item && run.lockedIds.includes(item.id)} onLock={()=>act({type:'lock',offerId:item.id})} onBuy={()=>buy(item)}/>)}</div><div className="mt-7 flex flex-wrap justify-center gap-3"><GameButton tone="dark" disabled={run.signal<cost} onClick={()=>act({type:'reroll'})}>Reroll unlocked • {cost}</GameButton><GameButton onClick={onContinue}>Start Wave {run.wave+1}</GameButton><GameButton tone="dark" onClick={onProfile}>Save & profile</GameButton></div><p className="mt-4 text-center text-xs text-game-muted">Every purchase, reroll, lock and upgrade updates the solo checkpoint. Refresh during combat returns to this boundary.</p><IntermissionInventory run={run}/></div>{pending && <PurchasePicker item={pending} run={run} onCancel={()=>setPending(null)} onConfirm={weaponId=>act({type:'buy',offerId:pending.id,...(pending.premium?{weaponId}:{replaceId:weaponId})})}/>}</main>;
}