import { useMemo, useState } from 'react';
import SiteNav from '@/components/game/SiteNav';
import { guideEntries } from '@/game/data/reference';
import OraclePortrait from '@/components/game/OraclePortrait';
import DonPortrait from '@/components/game/DonPortrait';
import EnemyPortrait from '@/components/game/EnemyPortrait';
import { characterSprite, enemySpriteDef } from '@/game/art/characterSprites';
export default function FieldGuide(){
  const sections=useMemo(guideEntries,[]),[tab,setTab]=useState('Controls'),[query,setQuery]=useState('');
  const entries=sections[tab].filter(e=>`${e.title} ${e.body}`.toLowerCase().includes(query.toLowerCase()));
  return <main className="game-grid min-h-screen px-5 pb-12 text-game-ink"><SiteNav/><section className="mx-auto max-w-6xl"><p className="mt-6 font-bold uppercase tracking-widest text-game-warm">Company-approved professional development</p><h1 className="mt-2 font-heading text-4xl font-bold">The Field Guide</h1><p className="mt-3 text-game-muted">Live reference from the current roster, combat data and tuning. No imaginary effects, no fictional enemy bullets.</p><label className="mt-6 block"><span className="sr-only">Search this guide tab</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${tab.toLowerCase()}…`} className="min-h-12 w-full rounded-xl border border-game-signal/30 bg-game-panel px-4 text-game-ink placeholder:text-game-muted focus:outline focus:outline-game-signal"/></label><div role="tablist" aria-label="Guide sections" className="my-5 flex flex-wrap gap-2" onKeyDown={e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const names=Object.keys(sections),offset=e.key==='ArrowRight'?1:-1,index=e.key==='Home'?0:e.key==='End'?names.length-1:(names.indexOf(tab)+offset+names.length)%names.length;setTab(names[index]);e.currentTarget.querySelectorAll('button')[index].focus()}}>{Object.keys(sections).map(name=><button key={name} role="tab" id={`guide-tab-${name}`} aria-controls="guide-panel" tabIndex={name===tab?0:-1} aria-selected={name===tab} className={`min-h-11 rounded-lg border px-4 font-bold ${name===tab?'border-game-signal bg-game-signal text-game-bg':'border-game-signal/25 bg-game-panel'}`} onClick={()=>setTab(name)}>{name}</button>)}</div><div role="tabpanel" id="guide-panel" aria-labelledby={`guide-tab-${tab}`} className="grid gap-4 md:grid-cols-2">{entries.map(e=><article key={e.id} className="rounded-2xl border border-game-signal/20 bg-game-panel p-5">{tab==='Characters' && e.id==='oracle' && <OraclePortrait name={e.title}/>}{tab==='Characters' && e.id==='don' && <DonPortrait name={e.title}/>}{tab==='Enemies' && enemySpriteDef(e.id) && <EnemyPortrait id={e.id} name={e.title}/>}{tab==='Bosses' && enemySpriteDef(e.id) && <EnemyPortrait id={e.id} name={e.title}/>}<h2 className="font-heading text-xl font-bold text-game-signal">{e.title}</h2><p className="mt-3 whitespace-pre-line text-sm leading-relaxed text-game-muted">{e.body}</p></article>)}</div>{!entries.length && <p className="rounded-xl bg-game-panel p-5">No matches in this tab. Try a shorter search or another tab.</p>}</section></main>;
}